image: jugit-registry.fz-juelich.de/fluxomics/hops

variables:
  GIT_SUBMODULE_STRATEGY: recursive


stages:
  - build
  - test

build-debug:
  stage: build
  script:
    - mkdir cmake-build-debug && cd cmake-build-debug && CXX=clang++ CC=clang cmake .. -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu -DCMAKE_BUILD_TYPE=Release -DHOPS_HDF5_SUPPORT=ON -DHOPS_BENCHMARKS=OFF && make -j 16 && cd -
  artifacts:
    paths:
      - cmake-build-debug
    expire_in: 2 days

build-release:
  stage: build
  script:
    - mkdir cmake-build-release && cd cmake-build-release && CXX=clang++ CC=clang cmake .. -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu -DHOPS_HDF5_SUPPORT=ON -DHOPS_HDF5_SUPPORT=ON -DCMAKE_BUILD_TYPE=Release -DHOPS_BENCHMARKS=OFF && make -j 16 && cd -
  artifacts:
    paths:
      - cmake-build-release
    expire_in: 2 days

test-debug:
  stage: test
  script:
    - cd cmake-build-debug && env CTEST_OUTPUT_ON_FAILURE=1 make test && cd -
  artifacts:
    when: always
    reports:
      junit: cmake-build-debug/tests/reports/*.xml
    expire_in: 10 weeks

test-release:
  stage: test
  script:
    - cd cmake-build-release && env CTEST_OUTPUT_ON_FAILURE=1 make test && cd -
  artifacts:
    when: always
    reports:
      junit: cmake-build-release/tests/reports/*.xml
    expire_in: 10 weeks

