dist: focal
sudo: true

env:
  global:
    - MAKEFLAGS="-j 2"

language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y apt-utils
  - sudo apt-get install -y build-essential 
  - sudo apt-get install -y software-properties-common 
  - sudo apt-get install -y cmake 
  - sudo apt-get install -y libeigen3-dev
  - sudo apt-get install -y libhdf5-dev
  - sudo apt-get install -y doxygen 
  - sudo apt-get install -y libsbml5-dev
  - sudo apt-get install -y libmpich-dev
  - sudo apt-get install -y libbz2-dev
  - sudo apt-get install -y coinor-libclp-dev 
  - sudo apt-get install -y libboost-all-dev 

script:
  - /usr/bin/mpiexec --help
  - mkdir -p cmake-build-debug
  - cd cmake-build-debug
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DHOPS_BENCHMARKS=OFF -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu
  - make
  - travis_wait 30 make test
  - cd .. 
  - mkdir -p cmake-build-release
  - cd cmake-build-release
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DHOPS_BENCHMARKS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu
  - make
  - travis_wait 30 make test
