dist: focal
sudo: true

language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y apt-utils
  - sudo apt-get install -y build-essential software-properties-common
  - sudo apt-get install -y libeigen3-dev liblpsolve55-dev lp-solve libncursesw5-dev
  - sudo apt-get install -y libxerces-c-dev libhdf5-dev  doxygen libncurses5-dev libsuitesparse-dev 
  - sudo apt-get install -y libsbml5-dev mpich libmpich-dev git bzip2 libbz2-dev libsbml5-dev
  - sudo apt-get install -y openmpi-bin openmpi-common libopenmpi-dev
  - sudo apt-get install -y coinor-clp coinor-libclp-dev
  - sudo snap install cmake --classic

script:
  - mkdir -p cmake-build-debug
  - cd cmake-build-debug
  - cmake -DHOPS_BENCHMARKS=OFF ..
  - make
  - travis_wait 30 make test
  - cd .. 
  - mkdir -p cmake-build-release
  - cd cmake-build-release
  - cmake -DCMAKE_BUILD_TYPE=Release -DHOPS_BENCHMARKS=OFF ..
  - make
  - travis_wait 30 make test
