#ifndef HOPS_MARKOVCHAINATTRIBUTE_HPP
#define HOPS_MARKOVCHAINATTRIBUTE_HPP

namespace hops {
    enum class MarkovChainAttribute {
        FISHER_WEIGHT,
        STEP_SIZE,
        PARALLEL_TEMPERING_COLDNESS,
        PARALLEL_TEMPERING_EXCHANGE_PROBABILITY
    };
}

#endif //HOPS_MARKOVCHAINATTRIBUTE_HPP
