#ifndef HOPS_MARKOVCHAINATTRIBUTE_HPP
#define HOPS_MARKOVCHAINATTRIBUTE_HPP

namespace hops {
    enum class MarkovChainAttribute {
        FISHER_WEIGHT,
        PARALLEL_TEMPERING_COLDNESS,
        PARALLEL_TEMPERING_EXCHANGE_PROBABILITY,
        PREVIOUS_STEP_ACCEPTANCE_PROBABILITY,
        STEP_SIZE,
    };
}

#endif //HOPS_MARKOVCHAINATTRIBUTE_HPP
