#ifndef HOPS_MARKOVCHAINATTRIBUTE_HPP
#define HOPS_MARKOVCHAINATTRIBUTE_HPP

namespace hops {
    enum class MarkovChainAttribute {
        PARALLEL_TEMPERING_COLDNESS,
        PARALLEL_TEMPERING_EXCHANGE_PROBABILITY,
        STEP_SIZE
    };
}

#endif //HOPS_MARKOVCHAINATTRIBUTE_HPP
